# ===================================================================
# CONFIGURAÇÃO DOS ENDPOINTS DA API DE EXPECTATIVAS (BOLETIM FOCUS)
# ===================================================================
# Este arquivo define a estrutura para consulta dos dados do Boletim
# Focus do Banco Central do Brasil. Cada entrada representa um
# endpoint da API, com seus respectivos parâmetros de consulta e
# campos de resultado.
# ===================================================================
database:
  type: sqlite
  db_name: dados_bcb.db

focus_endpoints:
  ExpectativasMercadoAnuais:
    nome_amigavel: "Expectativas de Mercado Anuais"
    descricao_endpoint: "Consulta as projeções anuais para os principais indicadores econômicos."
    parametros:
      Indicador:
        tipo: string
        descricao: "Selecione o indicador econômico desejado."
        opcoes:
          - Balança Comercial
          - Câmbio
          - Conta corrente
          - Dívida bruta do governo geral
          - Dívida líquida do setor público
          - IGP-DI
          - IGP-M
          - INPC
          - Investimento direto no país
          - IPA-DI
          - IPA-M
          - IPCA
          - IPCA Administrados
          - IPCA Alimentação no domicílio
          - IPCA Bens industrializados
          - IPCA Livres
          - IPCA Serviços
          - IPCA-15
          - IPC-FIPE
          - PIB Agropecuária
          - PIB Despesa de consumo da administração pública
          - PIB despesa de consumo das famílias
          - PIB Exportação de bens e serviços
          - PIB Formação Bruta de Capital Fixo
          - PIB Importação de bens e serviços
          - PIB Indústria
          - PIB Serviços
          - PIB Total
          - Produção industrial
          - Resultado nominal
          - Resultado primário
          - Selic
          - Taxa de desocupação
      IndicadorDetalhe:
        tipo: string
        descricao: "Detalhe (apenas para Balança Comercial)."
        opcoes:
          - Exportações
          - Importações
          - Saldo
      Data:
        tipo: string # Na API é string, mas pode ser tratado como data
        descricao: "Data da coleta da expectativa."
      DataReferencia:
        tipo: string # Na API é string, mas representa o ano
        descricao: "Ano de referência da projeção."
      Media:
        tipo: number
        descricao: "Média das expectativas dos respondentes."
      Mediana:
        tipo: number
        descricao: "Mediana das expectativas dos respondentes."
      DesvioPadrao:
        tipo: number
        descricao: "Desvio padrão das expectativas."
      Minimo:
        tipo: number
        descricao: "Valor mínimo observado nas expectativas."
      Maximo:
        tipo: number
        descricao: "Valor máximo observado nas expectativas."
      numeroRespondentes:
        tipo: integer
        descricao: "Quantidade de instituições que responderam à pesquisa."
      baseCalculo:
        tipo: integer
        descricao: "Base de cálculo utilizada."

  ExpectativaMercadoMensais:
    nome_amigavel: "Expectativas de Mercado Mensais"
    descricao_endpoint: "Consulta as projeções mensais para os principais indicadores econômicos."
    parametros:
      Indicador:
        tipo: string
        descricao: "Selecione o indicador para a projeção mensal."
        opcoes:
          - Câmbio
          - IGP-DI
          - IGP-M
          - INPC
          - IPA-DI
          - IPA-M
          - IPCA
          - IPCA Administrados
          - IPCA Alimentação no domicílio
          - IPCA Bens industrializados
          - IPCA Livres
          - IPCA Serviços
          - IPCA-15
          - IPC-Fipe
          - Produção industrial
          - Taxa de desocupação
      Data:
        tipo: string
        descricao: "Data da coleta da expectativa."
      DataReferencia:
        tipo: string
        descricao: "Mês e ano de referência da projeção (formato 'mmm/yyyy')."
      Media:
        tipo: number
        descricao: "Média das expectativas dos respondentes."
      Mediana:
        tipo: number
        descricao: "Mediana das expectativas dos respondentes."
      DesvioPadrao:
        tipo: number
        descricao: "Desvio padrão das expectativas."
      Minimo:
        tipo: number
        descricao: "Valor mínimo observado nas expectativas."
      Maximo:
        tipo: number
        descricao: "Valor máximo observado nas expectativas."
      numeroRespondentes:
        tipo: integer
        descricao: "Quantidade de instituições que responderam à pesquisa."
      baseCalculo:
        tipo: integer
        descricao: "Base de cálculo utilizada."

  ExpectativasMercadoTrimestrais:
    nome_amigavel: "Expectativas de Mercado Trimestrais"
    descricao_endpoint: "Consulta as projeções trimestrais para o PIB."
    parametros:
      Indicador:
        tipo: string
        descricao: "Selecione o indicador para a projeção trimestral."
        opcoes:
          - Câmbio
          - IPCA
          - IPCA Administrados
          - IPCA Alimentação no domicílio
          - IPCA Bens industrializados
          - IPCA Livres
          - IPCA Serviços
          - PIB Agropecuária
          - PIB Indústria
          - PIB Serviços
          - PIB Total
          - Taxa de desocupação
      Data:
        tipo: string
        descricao: "Data da coleta da expectativa."
      DataReferencia:
        tipo: string
        descricao: "Trimestre e ano de referência da projeção (formato 't/yyyy')."
      Media:
        tipo: number
        descricao: "Média das expectativas dos respondentes."
      Mediana:
        tipo: number
        descricao: "Mediana das expectativas dos respondentes."
      DesvioPadrao:
        tipo: number
        descricao: "Desvio padrão das expectativas."
      Minimo:
        tipo: number
        descricao: "Valor mínimo observado nas expectativas."
      Maximo:
        tipo: number
        descricao: "Valor máximo observado nas expectativas."
      numeroRespondentes:
        tipo: integer
        descricao: "Quantidade de instituições que responderam à pesquisa."
      baseCalculo:
        tipo: integer
        descricao: "Base de cálculo utilizada."

  ExpectativasMercadoTop5Anuais:
    nome_amigavel: "Expectativas de Mercado Top 5 Anuais"
    descricao_endpoint: "Consulta as projeções anuais do grupo Top 5 (curto e médio prazo)."
    parametros:
      Indicador:
        tipo: string
        descricao: "Selecione o indicador."
        opcoes:
          - Câmbio
          - IGP-DI
          - IGP-M
          - IPCA
          - Selic
      Data:
        tipo: string
        descricao: "Data da coleta da expectativa."
      DataReferencia:
        tipo: string
        descricao: "Ano de referência da projeção."
      tipoCalculo:
        tipo: string
        descricao: "Selecione o tipo de cálculo (Curto / Médio / Longo)."
      Media:
        tipo: number
        descricao: "Média das expectativas dos respondentes do grupo Top 5."
      Mediana:
        tipo: number
        descricao: "Mediana das expectativas dos respondentes do grupo Top 5."
      DesvioPadrao:
        tipo: number
        descricao: "Desvio padrão das expectativas."
      Minimo:
        tipo: number
        descricao: "Valor mínimo observado nas expectativas."
      Maximo:
        tipo: number
        descricao: "Valor máximo observado nas expectativas."

  ExpectativasMercadoTop5Mensais:
    nome_amigavel: "Expectativas de Mercado Top 5 Mensais"
    descricao_endpoint: "Consulta as projeções mensais do grupo Top 5 (curto prazo)."
    parametros:
      Indicador:
        tipo: string
        descricao: "Selecione o indicador."
        opcoes:
          - Câmbio
          - IGP-DI
          - IGP-M
          - IPCA
      Data:
        tipo: string
        descricao: "Data da coleta da expectativa."
      DataReferencia:
        tipo: string
        descricao: "Mês e ano de referência da projeção (formato 'mmm/yyyy')."
      tipoCalculo:
        tipo: string
        descricao: "Tipo de cálculo (Curto / Médio / Longo)."
      Media:
        tipo: number
        descricao: "Média das expectativas dos respondentes do grupo Top 5."
      Mediana:
        tipo: number
        descricao: "Mediana das expectativas dos respondentes do grupo Top 5."
      DesvioPadrao:
        tipo: number
        descricao: "Desvio padrão das expectativas."
      Minimo:
        tipo: number
        descricao: "Valor mínimo observado nas expectativas."
      Maximo:
        tipo: number
        descricao: "Valor máximo observado nas expectativas."

  ExpectativasMercadoSelic:
    nome_amigavel: "Expectativas de Mercado Selic"
    descricao_endpoint: "Consulta as projeções para a taxa Selic nas reuniões do Copom."
    parametros:
      Indicador:
        tipo: string
        descricao: "Nome do indicador (Selic)."
        opcoes:
          - Selic
      Data:
        tipo: string
        descricao: "Data da reunião do Copom."
      Reuniao:
        tipo: string
        descricao: "Selecione a reunião do Copom."
        opcoes:
          - R1
          - R2
          - R3
          - R4
          - R5
          - R6
          - R7
          - R8
      Media:
        tipo: number
        descricao: "Média das expectativas para a Selic."
      Mediana:
        tipo: number
        descricao: "Mediana das expectativas para a Selic."
      DesvioPadrao:
        tipo: number
        descricao: "Desvio padrão das expectativas."
      Minimo:
        tipo: number
        descricao: "Valor mínimo observado nas expectativas."
      Maximo:
        tipo: number
        descricao: "Valor máximo observado nas expectativas."
      numeroRespondentes:
        tipo: integer
        descricao: "Quantidade de instituições que responderam à pesquisa."
      baseCalculo:
        tipo: integer
        descricao: "Base de cálculo utilizada."

  ExpectativasMercadoInflacao12Meses:
    nome_amigavel: "Expectativas de Mercado para Inflação 12 meses"
    descricao_endpoint: "Consulta as projeções de inflação para os próximos 12 meses."
    parametros:
      Indicador:
        tipo: string
        descricao: "Selecione o indicador de inflação."
        opcoes:
          - IGP-DI
          - IGP-M
          - INPC
          - IPA-DI
          - IPA-M
          - IPCA
          - IPCA Administrados
          - IPCA Alimentação no domicílio
          - IPCA Bens industrializados
          - IPCA Livres
          - IPCA Serviços
          - IPCA-15
          - IPC-FIPE
      Data:
        tipo: string
        descricao: "Data da coleta da expectativa."
      Suavizada:
        tipo: string
        descricao: "Indica se a expectativa é suavizada (ex: 'Sim' ou 'Não')."
        opcoes:
          - S
          - N
      Media:
        tipo: number
        descricao: "Média das expectativas."
      Mediana:
        tipo: number
        descricao: "Mediana das expectativas."
      DesvioPadrao:
        tipo: number
        descricao: "Desvio padrão das expectativas."
      Minimo:
        tipo: number
        descricao: "Valor mínimo observado nas expectativas."
      Maximo:
        tipo: number
        descricao: "Valor máximo observado nas expectativas."
      numeroRespondentes:
        tipo: integer
        descricao: "Quantidade de instituições que responderam à pesquisa."
      baseCalculo:
        tipo: integer
        descricao: "Base de cálculo utilizada."
  
  ExpectativasMercadoInflacao24Meses:
    nome_amigavel: "Expectativas de Mercado para Inflação 13 a 24 meses"
    descricao_endpoint: "Consulta as projeções de inflação para o período de 13 a 24 meses à frente."
    parametros:
      Indicador:
        tipo: string
        descricao: "Selecione o indicador de inflação."
        opcoes:
          - IGP-DI
          - IGP-M
          - INPC
          - IPA-DI
          - IPA-M
          - IPCA
          - IPCA Administrados
          - IPCA Alimentação no domicílio
          - IPCA Bens industrializados
          - IPCA Livres
          - IPCA Serviços
          - IPCA-15
          - IPC-FIPE
      Data:
        tipo: string
        descricao: "Data da coleta da expectativa."
      Suavizada:
        tipo: string
        descricao: "Indica se a expectativa é suavizada (ex: 'Sim' ou 'Não')."
        opcoes:
          - S
          - N
      Media:
        tipo: number
        descricao: "Média das expectativas."
      Mediana:
        tipo: number
        descricao: "Mediana das expectativas."
      DesvioPadrao:
        tipo: number
        descricao: "Desvio padrão das expectativas."
      Minimo:
        tipo: number
        descricao: "Valor mínimo observado nas expectativas."
      Maximo:
        tipo: number
        descricao: "Valor máximo observado nas expectativas."
      numeroRespondentes:
        tipo: integer
        descricao: "Quantidade de instituições que responderam à pesquisa."
      baseCalculo:
        tipo: integer
        descricao: "Base de cálculo utilizada."

  ExpectativasMercadoTop5Selic:
    nome_amigavel: "Expectativas de Mercado Selic Top 5"
    descricao_endpoint: "Consulta as projeções para a Selic do grupo Top 5."
    parametros:
      indicador:
        tipo: string
        descricao: "Nome do indicador (Selic)."
        opcoes:
          - Selic
      Data:
        tipo: string
        descricao: "Data da reunião do Copom."
      reuniao:
        tipo: string
        descricao: "Selecione a reunião do Copom."
        opcoes:
          - R1
          - R2
          - R3
          - R4
          - R5
          - R6
          - R7
          - R8
      tipoCalculo:
        tipo: integer
        descricao: "Tipo de cálculo (Curto / Médio / Longo)."
      media:
        tipo: number
        descricao: "Média das expectativas para a Selic."
      mediana:
        tipo: number
        descricao: "Mediana das expectativas para a Selic."
      desvioPadrao:
        tipo: number
        descricao: "Desvio padrão das expectativas."
      coeficienteVariacao:
        tipo: number
        descricao: "Coeficiente de variação das expectativas."
      minimo:
        tipo: number
        descricao: "Valor mínimo observado nas expectativas."
      maximo:
        tipo: number
        descricao: "Valor máximo observado nas expectativas."